# Generated by Django 4.2.7 on 2023-11-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="firstname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="lastname",
            field=models.CharField(max_length=100),
        ),
    ]
